### ISSUE TITLE
How about something for creating and assigning an IAM role to the server?

### ISSUE THREAD

**Issue by rberger** [chef/chef-provisioning-aws#1]
Have you thought about a mechanism that would allow the chef-metal provisioning run to create and assign an IAM role to the server being created?

**Comment by lantrix** [comment]
This means at the moment there is no way to provision a machine and allocate an IAM instance role to it (using machine_options)?

**Comment by pburkholder** [comment]
I'll take this to work on since I want it as well as one of my customers.

**Comment by kevindickerson** [comment]
:raised_hand: Dealing with this currently! :+1:

Although my question is, "how do I specifically tell a machine that it *doesn't* need to pass roles.

**Comment by davent** [comment]
Is there a known timescale for assigning an IAM Role to a newly created EC2 Instance? This would be extremely useful as we use IAM Roles extensively.

**Comment by pburkholder** [comment]
I am overcommitted on other work and can't do this. I have no idea if it's a major change or not, but I need to focus on other work.

**Comment by rberger** [comment]
I would be willing to work on this if I could get some orientation, documentation or other hints on how to properly extend chef-provisioning. I have some experience with Iam policy stuff from the AWS-Sdk side of things

**Comment by dblessing** [comment]
You can currently assign an IAM role to instances as part of `bootstrap_options` hash in `machine_options`:

```
bootstrap_options: {
    iam_instance_profile: {
      name: 'my_role'
    }
  }
```

**Comment by rberger** [comment]
Probably should create a new ticket. What I had in mind was the whole shebang of creating the role[s] and assigning policies to it.

**Comment by tyler-ball** [comment]
Closing this as it is covered by #224 and #225
