### ISSUE TITLE
Specified AMI not being used

### ISSUE THREAD

**Issue by jaconstantine** [chef/chef-provisioning-aws#102]
With chefdk 0.4.0-1 on Mac OS X 10.10.2

```ruby
require 'chef/provisioning'

with_driver 'aws'

with_machine_options :bootstrap_options => {
  :key_name => 'jgc_riak_usw1',
  :subnet =>   'subnet-ce799bab',
  :security_groups => ['jgc_riak_sg'],
  :instance_type => 'm3.medium',
  :image_id => 'ami-26505463'
}

machine 'test1' do
  recipe 'riak'
end
```

when I do ```$ chef-client -z ./provisioning-bug.rb```, I see:

```
...
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
...
Converging 1 resources
Recipe: @recipe_files::/Users/jaconstantine/Projects/API_Team/Properties_API/api-mobile-properties/provision_test_instance/provisioning-bug.rb
  * machine[test1] action converge
    - Create test1 with AMI ami-73717d36 in us-west-1
    - create node test1 at http://localhost:8889
    -   add normal.tags = nil
    -   add normal.chef_provisioning = {"location"=>{"driver_url"=>"aws", "driver_version"=>"0.2.1", "allocated_at"=>"2015-02-19 00:25:27 UTC", "host_node"=>"http://localhost:8889/nodes/", "image_id"=>nil, "instance_id"=>"i-b87a7370", "key_name"=>"jgc_riak_usw1"}}
    -   update run_list from [] to ["recipe[riak]"][2015-02-18T16:25:27-08:00] WARN: Server test1 has no public ip address.  Using private ip '10.139.5.105'.  Set driver option 'use_private_ip_for_ssh' => true if this will always be the case ...

    - waiting for test1 (i-b87a7370 on aws) to be connectable (transport up and running) ...
    - been waiting 0/120 -- sleeping 10 seconds for test1 (i-b87a7370 on aws) to be connectable ...
```

The default ami is always used.  The ami specified is private to my account and I can use it in the AWS console to launch instances.

**Comment by jkeiser** [comment]
That is passing strange.  Would you mind terribly trying this on master?  I know we've had several fixes around image_id specifications.  i.e. clone the chef-provisioning-aws repository and `rake install`, then try again.  If it recurs, and it could well recur, let us know :)  Either way, we'll take a look at this during the 1.0 push.

**Comment by jaconstantine** [comment]
OK, I cloned the repo, cd'd into it and did a ```bundle install --path chef/bundle```
```
...
Installing savon 0.9.5
Installing winrm 1.2.0
Using chef-provisioning 0.18 from https://github.com/opscode/chef-provisioning.git (at master)
Using chef-provisioning-aws 0.2.1 from source at .
Installing rspec-support 3.2.1
Installing rspec-core 3.2.0
Installing rspec-expectations 3.2.0
Installing rspec-mocks 3.2.0
Installing rspec 3.2.0
Using bundler 1.7.12
Your bundle is complete!
It was installed into ./chef/bundle
$ 
```
Then I ran:

```ruby
require 'chef/provisioning'

with_driver 'aws'

with_machine_options :bootstrap_options => {
  :availability_zone => 'us-west-1c',
  :key_name => 'jgc_riak_usw1',
  :subnet =>   'subnet-ce799bab',
  :security_groups => ['jgc_riak_sg'],
  :instance_type => 'm3.medium',
  :image_id => 'ami-26505463'
}

machine 'test2' do
  recipe 'mysql'
end
```

And got:

```
$ chef-client -z ./foo.rb 
[2015-02-23T13:36:44-08:00] WARN: No config file found or specified on command line, using command line options.
[2015-02-23T13:36:44-08:00] WARN: No cookbooks directory found at or above current directory.  Assuming /Users/jaconstantine/Projects/API_Team/Properties_API/api-mobile-properties/chef-provisioning-test/chef-provisioner-aws-bug/chef-provisioning-aws.
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2015-02-23T13:36:47-08:00] WARN: Node SFO-JCON-M.sea.corp.expecn.com has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/jaconstantine/Projects/API_Team/Properties_API/api-mobile-properties/chef-provisioning-test/chef-provisioner-aws-bug/chef-provisioning-aws/foo.rb
  * machine[test2] action converge
    - Create test2 with AMI ami-73717d36 in us-west-1
    - create node test2 at http://localhost:8889
    -   add normal.tags = nil
    -   add normal.chef_provisioning = {"location"=>{"driver_url"=>"aws", "driver_version"=>"0.2.1", "allocated_at"=>"2015-02-23 21:37:18 UTC", "host_node"=>"http://localhost:8889/nodes/", "image_id"=>nil, "instance_id"=>"i-7bf6e3b3", "key_name"=>"jgc_riak_usw1"}}
    -   update run_list from [] to ["recipe[mysql]"][2015-02-23T13:37:18-08:00] WARN: Server test2 has no public ip address.  Using private ip '10.139.5.39'.  Set driver option 'use_private_ip_for_ssh' => true if this will always be the case ...
^C
```

**Comment by jedugas** [comment]
Had the same issue (using the default / ubuntu-trusty ami despite specifying one) just today with fresh a provisioning gem. For me, the fix was to change the ini section in my  ~/.aws/config file. (was using the  'profile ' prefix based on http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files)

instead of...

    [profile somename]
    region=us-east-1
    output=json

i used...

    [somename]
    region=us-east-1
    output=json

Very surprised this actually worked - had expected the value I provided in the driver_url to take precedence

    with_driver "aws:virginia:us-east-1"
    ...

given this snippet from driver.rb

    def initialize(driver_url, config)
      super

      _, profile_name, region = driver_url.split(':')
      profile_name = nil if profile_name && profile_name.empty?
      region = nil if region && region.empty?

      credentials = profile_name ? aws_credentials[profile_name] : aws_credentials.default
      @aws_config = AWS::Core::Configuration.new(
        access_key_id:     credentials[:aws_access_key_id],
        secret_access_key: credentials[:aws_secret_access_key],
        region: region || credentials[:region]
      )
    end

**Comment by jaconstantine** [comment]
This is still an issue, and worse, none of the code that used to at least do something, does nothing at all now!

**Comment by tyler-ball** [comment]
Hey @jaconstantine - can you try this with the [latest prerelease](https://github.com/chef/chef-dk#pre-release-candiates) ChefDK?  You should also update your first 2 statements to look like the following:

```ruby
require 'chef/provisioning/aws_driver'

with_driver 'aws::us-west-1'
```

How does it perform when you do that?

**Comment by tyler-ball** [comment]
Closing this since its been a while since we got feedback.  Please re-open if you still experience this issue in the latest ChefDK!
