### ISSUE TITLE
No address associated with hostname" when using a proxy?

### ISSUE THREAD

**Issue by lcc2207** [chef/chef-provisioning-aws#103]
Is anyone else seeing this error behind a proxy servers

command run - "chef-client -z test2.rb

 ================================================================================
    Error executing action `converge` on resource 'machine[test2]'
    ================================================================================

    SocketError
    -----------
    getaddrinfo: No address associated with hostname

    Resource Declaration:
    ---------------------
    # In /apps/test.rb

**Comment by jkeiser** [comment]
I know we have confirmation that convergence is working behind proxies.  Can you try again with the latest version of chef-provisioning and chef-provisioning-aws (released last night)?  And if that's not working, can you provide some information about how you are configuring your proxy and what your recipe looks like?

**Comment by lcc2207** [comment]
confirmed the updated version resolved my issues.
