### ISSUE TITLE
Allow specifying health check on ELB

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#107]
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#configure_health_check-instance_method

**Comment by danieljimenez** [comment]
+1

**Comment by buererra** [comment]
(thumbsup)

**Comment by danieljimenez** [comment]
bump, ELBs are tough to use without health checks set right.

**Comment by danieljimenez** [comment]
If anyone could kindly give me a push start for this, I maybe able to work on it some this week.

**Comment by tyler-ball** [comment]
@danieljimenez any chance you could make it to office hours this Thursday at 1pm PST?  We could get started on it in there!

**Comment by danieljimenez** [comment]
Hi Tyler, 

When would the next office hours be?

**Comment by tyler-ball** [comment]
The next office hours are Thursday July 30th at 1pm PST.  They are coordinated via http://www.meetup.com/Chef-Office-Hours/events/223831967/

**Comment by lynchc** [comment]
+1
