### ISSUE TITLE
Unable to set subnet on a load_balancer.

### ISSUE THREAD

**Issue by lfjewett** [chef/chef-provisioning-aws#115]
I'm trying to learn how to use chef-provisioning with AWS and have run into a snag no amount of web searching has solved.  I took this code mostly from the examples here on this page but as we have several different VPC's I must be able to set which subnet Hosts and Load Balancers are in.  No matter what I do the Load Balancer ends up in our default subnet and I end up with an error saying the Host and LB are not in the same VPC.
```
  load_balancer "testlb-aws01" do
               load_balancer_options :availability_zones => ['us-east-1a'],
                          :listeners => [{
                               :port => 80,
                               :protocol => :http,
                               :instance_port => 8080,
                               :instance_protocol => :http,
                           }],
                           :subnet => ['subnet-z5555555']
    machines ['testvm-aws01']
  end
```
If this isn't a 'bug' and in fact is just my terrible understanding of the code is there any good resource for what options are allowed and how to set them.  The README is empty and the web has virtually nothing on chef-provisioning-aws.

**Comment by jkeiser** [comment]
The API is a passthrough for the corresponding AWS API, and you can find the docs on the relevant method here: http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/LoadBalancerCollection.html#create-instance_method

@tyler-ball, I know you were digging in this area--I'm pretty sure you found that subnet and availability_zones are mutually exclusive, ya?

@lfjewett, I see two issues: first, `:subnet` should be `:subnets` (plural), and second, I think you can't specify `:availability_zones` and `:subnets` at the same time; can you try fixing the `:subnets` key and removing `:availability_zones` and see what happens?

**Comment by lfjewett** [comment]
@jkeiser, Thank you for the reply and the link to the documentation.  I tried as you suggested and added an 's' to subnet and removed the availability_zones line but ended up with;
```
    AWS::ELB::Errors::ValidationError
    ---------------------------------
    Either AvailabilityZones or SubnetIds must be specified
```

I noticed on the available documentation that it says, :availability_zones (required, Array) so I tried with both availability_zones AND subnets and I got a working Load Balancer but again in the default subnet instead of the one specified.

**Comment by jkeiser** [comment]
Can you show me the output and recipe for the first thing you did (removed azs and added subnets)?

**Comment by lfjewett** [comment]
Sure!.

Code:
```
require 'chef/provisioning'
with_driver 'aws'

with_data_center 'us-east-1' do
  machine 'testapp-web-aws01' do
    options = {:bootstrap_options => {
        :key_name => 'name',
        :instance_type => 't2.micro',
        :associate_public_ip_address => false,
        :subnet => "subnet-f#######",
        :security_group_ids => ['sg-########']
        },
    :image_id => 'ami-########',
    :ssh_username => 'euser'
    }
    machine_options options
    tag 'Testing'
    converge true
  end

  load_balancer "testapp" do
    load_balancer_options :subnets => ['subnet-f#######'],
                          :listeners => [{
                               :port => 80,
                               :protocol => :http,
                               :instance_port => 8000,
                               :instance_protocol => :http,
                           }]
    machines ['testapp-web-aws01']
  end
end
```

Output (removed actual subnet ##): http://pastebin.com/CsD1h8Lm

**Comment by jkeiser** [comment]
Damn straight, that looks right.  Moving this to ready ... I *suspect* it's fixed by at least one of the pending PRs :)  @tyler-ball, do you think your patch might do it?

**Comment by tyler-ball** [comment]
Yes, I think this should be fixed by https://github.com/chef/chef-provisioning-aws/pull/108 - @lfjewett if you could try your code with my branch from that PR, I would appreciate the additional testing.

**Comment by lfjewett** [comment]
@tyler-ball I upgraded to the 0.4.0 release today as soon as I saw it was published and gave the code a shot.  Everything went perfectly.  I ran a few tests with different subnets and combinations but did not have any failures, I think this issue can be closed.

**Comment by tyler-ball** [comment]
Yay!
