### ISSUE TITLE
Machines and images report connectable even if they time out

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-provisioning-aws#122]
This appears to be an endemic problem.

https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L865

**Comment by ikozel** [comment]
Image and machine buildout definitely exceeding current constance value for max_wait_time especially with long run list for the nodes.

**Comment by dblessing** [comment]
Any update on this issue? It causes lots of pain :) Also, I don't think that code reference is the correct location anymore.

**Comment by tyler-ball** [comment]
Is the issue with the `wait_for_machine` method?  I would love to have a stacktrace for this one to understand what is going on.

**Comment by tyler-ball** [comment]
I'm going to close this for now since there is no stack trace and I don't understand the issue.  If anyone sees it again, please re-open!
