### ISSUE TITLE
Converge fails if instance is deleted

### ISSUE THREAD

**Issue by john-casey** [chef/chef-provisioning-aws#125]
If there is an error or someone deletes an instance from the AWS console, chef-provisioning-aws gets wigged out and cannot deal with the cached AWS image-id not being found. Since this is a converge, it should just converge ...

``` ================================================================================
    Error executing action `converge` on resource 'machine[elastichef-app-dev-1]'
    ================================================================================
    
    AWS::EC2::Errors::InvalidInstanceID::NotFound
    ---------------------------------------------
    The instance ID 'i-df14952f' does not exist
```

**Comment by jkeiser** [comment]
Super weird.  I bet fixed in master.  If you are able to check out master of chef-provisioning-aws and try there, that would be a huge help, otherwise we'll try it out ourselves in the near future :)

**Comment by jkeiser** [comment]
Yep, fixed in master!
