### ISSUE TITLE
Cannot refer to a security group by security_group_id

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#128]
Testing with latest master (0.4)

Use case is to set up a security group where anything within the security group is allowed to talk to anything else in the same security group. I used to refer to security_group_id, but that is now nil at the time that apply_rules is called (dont know if it gets set later).  Not a huge problem because changing to use logical name works ok, just may break some folks.

```
aws_security_group "provisioning-vpc-security-group" do
    inbound_rules lazy{ [
    {:ports => 22, :protocol => :tcp, :sources => ["0.0.0.0/0" ] },
    {:ports => 3001, :protocol => :tcp, :sources => ["0.0.0.0/0" ] },
     {:ports => 1024..65535, :protocol => :tcp, :sources => [ { :group_id => security_group_id } ] } 
     # {:ports => 1024..65535, :protocol => :tcp, :sources => [ "provisioning-vpc-security-group" ] } 

    ]}
    outbound_rules [
    { :sources => ["0.0.0.0/0" ] }

    ]
    vpc "provisioning-vpc"
  end
```

**Comment by zeroXten** [comment]
I get the following error when trying to use the  logical name:

    AWS::EC2::Errors::InvalidParameterValue
    ---------------------------------------
    invalid CIDR subnet specification: load-balancers

For aws security group "load-balancers":

    aws_security_group("load-balancers") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      id "load-balancers"
      security_group_id "sg-361d8052"
      driver "aws"
      declared_type :aws_security_group
      cookbook_name "@recipe_files"
      .....

One of the rules looks like:

    {:ports=>"9080", :protocol=>:tcp, :sources=>["load-balancers"]}

**Comment by jkeiser** [comment]
This is again a thing that latest master (today) is super likely to have fixed.  Sorry to respond to so many bugs with "can you try again on master," but ... can you try again on master?  Thanks :)

**Comment by jkeiser** [comment]
Logical name references definitely work now; I believe physical name works as well.

**Comment by christinedraper** [comment]
Cool, worked for me on master
