### ISSUE TITLE
AWS::AutoScaling::Errors::ValidationError: At least one Availability Zone or VPC Subnet is required.

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#135]
```
aws_auto_scaling_group "appserver_group" do
  launch_configuration 'appserver_config'
  max_size(2)
  min_size(1)
  desired_capacity(1)
  load_balancers(["appserver-elb"])
end
```

Fails with:
```
ERROR: aws_auto_scaling_group[appserver_group] (@recipe_files::/home/christine/provisioning/awsgen/aws_mod_v1.rb line 36) had an error: AWS::AutoScaling::Errors::ValidationError: At least one Availability Zone or VPC Subnet is required.
```

It didn't use to!

**Comment by ikozel** [comment]
@christinedraper  works for me with subnet:

aws_auto_scaling_group 'provisioning-test-auto-scaling-group' do
  availability_zones ['us-east-1e']
  desired_capacity 2
  min_size 1
  max_size 3
  launch_configuration 'provisioning-test-launch-configuration'
  load_balancers 'provisioning-test-elb'
  options subnets: 'subnet-x185ba9w'
end

**Comment by christinedraper** [comment]
I know it works with a subnet. It used to work without being explicit - at least it seemed to.

**Comment by christinedraper** [comment]
Closing based on avail zone being required by AWS sdk.

**Comment by Kajalk-k** [comment]
@christinedraper  Did it work after providing the avail zones?

**Comment by christinedraper** [comment]
@Kajalk-k  I think so but it was a very long time ago!
