### ISSUE TITLE
ELB attributes not supported

### ISSUE THREAD

**Issue by dblessing** [chef/chef-provisioning-aws#138]
ELB load balancer attributes are not supported. This is the only way to enable "cross-zone load balancing" on an ELB. See http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#modify_load_balancer_attributes-instance_method

An example of how this would likely be defined in Chef:

```
load_balancer 'my_elb' do
  load_balancer_options(
    load_balancer_attributes: {
      cross_zone_load_balancing: {
        enabled: true,
      },
    }
  )
end
```

**Comment by dblessing** [comment]
Actually, `cross_zone_load_balancing` isn't required to balance services in multiple AZs. It's still a nice to have, but not critical to general usage at this point.

**Comment by tyler-ball** [comment]
Solved by https://github.com/chef/chef-provisioning-aws/pull/199 - Thanks @dblessing!
