### ISSUE TITLE
local_route method doesn't exist in aws_route_table

### ISSUE THREAD

**Issue by msonnabaum** [chef/chef-provisioning-aws#180]
It's used in docs/examples/aws_vpc_complete.rb.

I think it's supposed to be `routes "0.0.0.0/0" => :internet_gateway`, but I'm not entirely sure.

**Comment by dblessing** [comment]
Yes, it's `routes` instead of `local_route`. From experience I can tell you you're better off looking at the resource definitions than the docs at the moment. They need updated a lot because this project has moved so quickly.

**Comment by georgecook-cbt** [comment]
In a VPC, I get an error using 'routes' saying it's not supported. It seems to like 'main_routes' better. I have not tested 'routes' outside of a VPC.

**Comment by tyler-ball** [comment]
I deleted the `aws_vpc_complete.rb` example because it was out of date (and incomplete).  But the `aws_vpc.rb` example works correctly.
