### ISSUE TITLE
enhance aws_ebs_volume :availability_zone to accept an AZ letter designation

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#184]
Currently, the fully qualified az must be provided `(ex. us-west-2a)`.  The attribute should be able to accept just the letter designation and use the current region to derive the full AZ name.  The attribute should continue to accept a fully qualified availability zone.

**Comment by patrick-wright** [comment]
I excluded the feature that allows the ability to include the full availability zone since volumes can not be created in another region other than the connected region.

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-provisioning-aws/pull/185
