### ISSUE TITLE
Tags are not converging idempotently

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#205]
They keep re-creating existing tags

**Comment by patrick-wright** [comment]
@tyler-ball hmm.  Do the tag specs fail too?

**Comment by patrick-wright** [comment]
I just ran the specs and they are passing. Could you provide a bit more detail so I can take a look? Thanks!

**Comment by tyler-ball** [comment]
I was running a local cookbook to see these errors - I've got a PR incoming with an updated `ref_full.rb` which includes tags on everything.
