### ISSUE TITLE
root ebs volumes should inherit aws tags from launched instance

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#206]
@cwebberOps has requested that root ebs volumes that are created and attached along with launching an instance will inherit the tags of that instance.  This issue is intended detail the requirements before starting the work.

Instance (machine) tags can by configured by setting the `:aws_tags` hash key when passed to the `#with_machine_options` method or a machine resource's `machine_options` attribute. Here are some initial questions:

1. Should the root volume only inherit tags upon launch?  Managing the tags on the ebs root volume to be in sync with updated instance tags may prove problematic.  Especially if the root ebs volume is being tagged separately.
1. How should the root ebs volume handle the instance 'Name' tag? For now, I think it can be ignored.
1. Should this be a configurable machine option? `:tag_ebs_root  => true` or similar.

@tyler-ball Your input would be appreciated :)

**Comment by tyler-ball** [comment]
My first question is: when scraping EBS volume usage information can we just look at the associated machine and examine the tags on that?  This wouldn't work for orphan disks, but there probably won't many of those.

Having said that it does seem totally reasonable to copy the tags from an instance to the default volume created.  I don't think we should try automatically managing the tags for any volume where there is going to be a discrete `aws_ebs_volume`.

I don't think we should try to sync the tags from an instance to a volume other than during the initial machine create.  So even if a `machine` resource has its `aws_tags` updated, those updated tags would not sync down to the default-created disc.  Trying to perform this ongoing sync brings a lot of edge cases into play that greatly expand scope.

To your second point, I agree - I don't think we mess with the `Name` tag.  Instead I would rather have a tag like `Created-By: i-123456`.  There is precedence for doing this (VPC manages an internet gateway) so we should look at the name of existing tags and copy those, unless there is a specific use case that requires a `X-*` tag name format.

And on point 3 - I think it makes sense for it to be configurable (with a default of `true`) but I say we leave it out for now for the following reasons:

1) We cannot update the `machine` resource in chef-provisioning without exposing it to all the other drivers
b) I don't want to add more extraneous information to the `:bootstrap_options` than there already is - that hash is getting nasty

**Comment by cwebberOps** [comment]
So a couple of things... There are actually TONS of orphan disks. It is actually quite depressing. 

The key with tagging the EBS volumes is that it gives us visibility in Ice (it is a relatively common OSS package for getting data about your AWS spend). And since we are using a tool, it's constraints are what we are stuck with. In this case, it doesnt have a way to do the recursive lookup of what instance the ebs volume belongs to.

I am totally on point, discrete ebs volumes shouldnt get auto tagged. Auto tagging should just occur on bootstrap of a new machine instance.

I love the Created-By Ideal. Given the number of times I have had to deal with orphaned EBS volumes, that is just a sane default.

**Comment by dushyant28** [comment]
Do we have any progress made on this ? SI there any way I can use something like aws_tags with aws_ebs_volumes ?

My requirement is that i want to have a custom tag "Backup" which is set to true. We have a script which automatically picks up the volumes with theses and take snapshots.

Any help is appreciated !

**Comment by patrick-wright** [comment]
@dushyant28 I believe the solution we implemented to tag ebs volumes is to use the aws_tags attribute which is available for all taggable resources.

```ruby
aws_ebs_volume 'ref-volume' do
  aws_tags :chef_type => "aws_ebs_volume"
end
```

**Comment by dushyant28** [comment]
Thanks a lot :)

**Comment by dushyant28** [comment]
Who do i tag the root EBS for a newly created instance created by the machine resource ?
