### ISSUE TITLE
Cannot find AWS Credentials

### ISSUE THREAD

**Issue by chrdunne** [chef/chef-provisioning-aws#210]
I am setting up a demo of provisioning with AWS. Using ChefDk 0.6.0, Chef-client 12.3.0
I have a provisioner node set up, bootstrapped, and I am using hosted chef.
I have assigned a simple provisioning recipe to the provisioner node.
I have copied my aws config and credentials files to the ~/.aws directory on the provisioner node.
When I run the chef-client I get
"No credentials loaded!  Do you have a ~/.aws/config?"

My recipe is 
```ruby
require "chef/provisioning"
with_driver "aws"
name = "chris"
with_machine_options({
  :bootstrap_options => {
    :instance_type => "t1.micro",
    :key_name => "ChefAWSProvisioningTest"
  },
  :ssh_username => "ubuntu",
  :image_id => "ami-4ab46b3d"
})

machine "#{name}-webserver-1" do
  recipe "webserver"
  tag "my-webserver"
  converge true
end
```

Any help would be greatly appreciated?

**Comment by pburkholder** [comment]
Hi Chris - Your recipe looks correct, I can run it w/o any errors related to my ~/.aws/config. Can you install the aws-cli on the same node and see if those tools also have config-related authentication issues?

http://docs.aws.amazon.com/cli/latest/userguide/installing.html

--Peter

**Comment by tyler-ball** [comment]
@chrdunne I will echo @pburkholder - thats a good debugging step.  Are you sure the file/folder is readable by the user running `chef-client`?

**Comment by chrdunne** [comment]
I recreated by aws config and all is working now on an ubuntu environment. I get different errors when running the chef-client in local-mode on a windows host. 

openssl::ssl::sslerror: ssl_connect returned=1 errno=0 state=sslv3 read server certificate b: certificate verify failed

This happens I believe at the step where the newly provisioned node is trying to connect back to the chef-server to install its own chef-client.

**Comment by tyler-ball** [comment]
@chrdunne that is a known Windows error with ChefDK 0.6.0 - can you try with 0.6.2?  We specifically put out 0.6.2 to fix that SSL error (that is the only difference between 0.6.0).

I'm going to close this since you got your config working.  But let us know if 0.6.2 does't fix your SSL issue!
