### ISSUE TITLE
from_image doesnt seem to work

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#211]
In the following, from_image doesn't seem to work. Instead I get a machine created with the default AMI.

```
# Associate resource with existing image ID
machine_image "ami-97ba9aa7" do
  action :nothing
end

# This isnt working - it uses default ami
machine "new_machine" do
  from_image "ami-97ba9aa7"
  chef_server( :chef_server_url => 'http://localhost:8889') # workaround chef-zero problem
end

# This works fine - uses specified existing image
aws_launch_configuration "appserver_config" do
  image 'ami-97ba9aa7'
  instance_type "t1.micro"
end

aws_auto_scaling_group "appserver_group" do
  launch_configuration 'appserver_config'
  availability_zones ["us-west-2c", "us-west-2a", "us-west-2b"]
end
```

I also tried the more basic case, with the same result (new_machine created with default AMI, not with new_image):
```
machine_image "new_image" do
  chef_server( :chef_server_url => 'http://localhost:8889')  # workaround chef-zero problem
end

machine "new_machine" do
  from_image "new_image"
  chef_server( :chef_server_url => 'http://localhost:8889')  # workaround chef-zero problem
end
```

**Comment by christinedraper** [comment]
I tested the basic case again on chef-provisioning-aws 1.2.1 and chef-provisioning-1.3.0.dev.0. It still ignores the "from_image" and creates a machine with the default AMI

**Comment by tyler-ball** [comment]
Yup, this is definitely a bug - closing in favor of https://github.com/chef/chef-provisioning-aws/issues/193 which is the same issue.  I'll move your relevant comments over there.  Thanks @christinedraper !
