### ISSUE TITLE
Route53 Zone

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#226]
AC: The ability to CRUD hosted zones, with an attribute for `private` and `records`.

A pending question is whether we add an action for `:only_add` where we don't blow away the default records, or whether we only support converging to _exactly_ the records specified.

Replicates https://github.com/chef/chef-provisioning-aws/issues/66
There is an existing resource that can be examined - https://github.com/hw-cookbooks/route53

**Comment by dblessing** [comment]
What do you mean by `routes`? Route 53 is just DNS so I think you mean `records`? Each `record` could be an independent resource so no need to worry about `:only_add` and other merging concerns, right?

**Comment by tyler-ball** [comment]
@dblessing right you are, `records` instead of `routes`.  I'm envisioning the resource looking like
```ruby
aws_hosted_zone "my_zone" do
  private true
  records {
    :type => 'A', ...
  }
end
```

Where `records` is a hash listing the records to converge to.  I'm thinking that records are an attribute on the zone since they can't exist independently.

**Comment by dblessing** [comment]
Ah, I see what you're saying. Personally, I much prefer the separate resources because I might not always define the records at the same time the zone is created. Currently we use the https://github.com/promisedlandt/cookbook-amazon_dns cookbook and have record resources sprinkled throughout our recipes wherever it makes most sense.

**Comment by tyler-ball** [comment]
@dblessing Thanks for linking that!  We'll definitely keep that use case in mind.  Are there any other AWS cookbooks you use to manage resources that chef-provisioning doesn't handle now?

**Comment by randomcamel** [comment]
Let's go with Route53's object model:

- `Zone` or `HostedZone`
- `RecordSet`

We could make our own `Record` object--IME individual DNS records have enough possible fields that a hash can suddenly get unwieldy.

**Comment by metadave** [comment]
Does using `private` as an attribute name present any problems?

**Comment by randomcamel** [comment]
Ruby appears to be content with `private` as an instance method name, so I think it'd be okay technically.

**Comment by metadave** [comment]
Ok, as long as it's not confusing to users.

**Comment by tyler-ball** [comment]
:-1: to using `private` as an instance method name because I think it would be confusing to ruby writers.  Could you use something like `restricted` or `secret` instead?

**Comment by gmiranda23** [comment]
For AWS users, my concern would be introducing nomenclature that doesn't match what Route53 uses.  How about still preserving Route53's naming convention by setting a zone type like so...

    aws_hosted_zone "my_public_zone" do
      type 'public'
      records {
        :type => 'A', ...
      }
    end
    
    aws_hosted_zone "my_private_zone" do
      type 'private'
      records {
        :type => 'A', ...
      }
    end

**Comment by metadave** [comment]
+1 @gmiranda23

**Comment by randomcamel** [comment]
@jkeiser and I started hacking on this. Creating and deleting a zone is pretty straightforward; RecordSets are more complex, but I'll start in on those as soon as zones are stable and tested.

**Comment by lynchc** [comment]
https://gist.github.com/lynchc/1a68c0e2b7bd2434eb58

not sure if there's anything in there you want to use but this is how far I got before I had to shelve it

**Comment by tyler-ball** [comment]
@lynchc This is the branch that @randomcamel started https://github.com/chef/chef-provisioning-aws/tree/cd/route53

**Comment by randomcamel** [comment]
The first pass at this has been merged to master, and development continues in the `cd/route53` branch, currently focused on softening a few rough edges. `docs/examples/route53.rb` has the DSL, and suggestions are welcome.

**Comment by lynchc** [comment]
awesome man. great work. I finished re-writing hosted zones and had moved on to recordsets when I got pulled into a different project and all my free-time was taken. Can't wait to throw this into my recipes now.

**Comment by tyler-ball** [comment]
CLosing this because https://github.com/chef/chef-provisioning-aws/pull/352 was just merged to master!
