### ISSUE TITLE
Access DNS_NAME more simply on Load Balancers

### ISSUE THREAD

**Issue by danieljimenez** [chef/chef-provisioning-aws#242]
Right now it's entirely too difficult to reference the most important part of a load balancer, it's DNS name. I've been pointed to several strategies including:

```
  ruby_block do
    block do
      public_load_balancer = Chef::Resource::AwsLoadBalancer.get_aws_object("#{env_name}-#{'public'}",
                                                                            driver: run_context.chef_provisioning.current_driver,
                                                                            run_context: run_context,
                                                                            managed_entry_store: Chef::Provisioning.chef_managed_entry_store(run_context.cheffish.current_chef_server)).dns_name
    end
  end
```

and

```
lb = aws_load_balancer "elbname"
lb.dns_name
```

all which have issues depending on when/where you run them. I'm trying to pass the value of this in as an attribute, and finding it to be very difficult to come to a working solution.

**Comment by danieljimenez** [comment]
Documenting attempt and failures here for my sanity:

```
  ruby_block 'fails' do
    block do
      public_elb = Chef::Resource::AwsLoadBalancer.get_aws_object("#{env_name}-public",
                                                                  driver: run_context.chef_provisioning.current_driver,
                                                                  run_context: run_context,
                                                                  managed_entry_store: Chef::Provisioning.chef_managed_entry_store(run_context.cheffish.current_chef_server)).dns_name
    end
  end
```

The above doesn't work because you get the error:
```
undefined method `elb' for nil:NilClass
```

**Comment by danieljimenez** [comment]
```
Chef::Resource::AwsLoadBalancer.get_aws_object("#{env_name}-public",
                                                                  driver: run_context.chef_provisioning.current_driver,
                                                                  run_context: run_context,
                                                                  managed_entry_store: Chef::Provisioning.chef_managed_entry_store(run_context.cheffish.current_chef_server)).dns_name
```

The above works great, except when the load balancer hasn't been created yet.

**Comment by danieljimenez** [comment]
```
  machine_batch 'Converge Instances' do
    all_machines.each do |machine_name|
      machine machine_name do
        converge true
        attributes lazy { {
                       foreflight: {
                           environment: {
                               remote_endpoints: {
                                   public_host_address: Chef::Resource::AwsLoadBalancer.get_aws_object("#{env_name}-web",
                                                                                                       driver: run_context.chef_provisioning.current_driver,
                                                                                                       run_context: run_context,
                                                                                                       managed_entry_store: Chef::Provisioning.chef_managed_entry_store(run_context.cheffish.current_chef_server)).dns_name
                               }
                           }
                       }
                   } }
      end
    end
  end
```

The above fails:
```

```

**Comment by danieljimenez** [comment]
It seems any form of running this in a lazy (either attributes or message in log), or a ruby_block causes thei undefined method 'elb' error.

**Comment by danieljimenez** [comment]
I believe I may have found the root cause, it appears when accessing the ELB that way, the Chef Zero URL hit is `http://localhost:8890/data/loadbalancers/skylab-web` but I believe it should be `http://localhost:8890/data/load_balancer/skylab-web`. It appears that way in the other requests anyways, does this make sense to y'all? @tyler-ball @christinedraper @jkeiser

**Comment by danieljimenez** [comment]
Ah-ha! It appears `run_context.chef_provisioning.current_driver` is in correct, causing driver to be nil. Right now I'm hand entering this as a work around.

**Comment by christinedraper** [comment]
Afraid I havent had time to try this out, but looking at the load_balancer code

https://github.com/chef/chef-provisioning/blob/4638bdf99e048452b5b80e06c118ba2a0a0132a3/lib/chef/resource/load_balancer.rb

it seems like it may still be using chef_metal name space. So you may find that `run_context.chef_metal.current_driver` works.

It may also work if you reference the @driver attribute from the load_balancer resource itself (and maybe this will be less prone to change downstream).  

@tyler-ball would be great to go through this one in office hours - this really is something that needs to be dead easy to do!

**Comment by danieljimenez** [comment]
Thanks @christinedraper. My preference would be to get the load balancer's DNS name through Chef Search.

**Comment by christinedraper** [comment]
I can see the attraction of using Chef search for key properties that are static for the lifetime of the resource, although it may be on a slippery slope of caching properties in Chef data bags rather than looking them up.  

I'd find it useful to have a lookup interface that pushed down more directly on the provider API, e.g.

`lookup ("aws", "aws_instance", "id:xxxx")`  - return aws instance with given instance id
`lookup ("aws", "aws_load_balancer", "name:xxxx")`  - return aws_load_balancer with given resource name

although I guess there's a load of subtlety in this about scoping -  would it only return resources known to Chef, or any that it finds through the provider's API? 

So I guess something that actually let me do something as simple as:

lb.aws_object

within a ruby block or lazy, without passing in driver, context, etc, would be fine for many cases.

**Comment by danieljimenez** [comment]
Look up would work too, preferably only returning things Chef knows about for safety's sake. Also I tried `run_context.chef_metal.current_driver` and received the same error about `elb` being `nil`. It seems like chef_metal and chef_provisioning are aliased.

**Comment by danieljimenez** [comment]
My assumption would be that all Load Balancers would have DNS names, or at least an IP address so having that data in search would be particularly useful.

**Comment by tyler-ball** [comment]
This will be fixed by adding the `aws_object` method the `machine`, `machine_batch` and `load_balancer` resources as part of https://github.com/chef/chef-provisioning-aws/pull/346 - see https://github.com/chef/chef-provisioning-aws/pull/346#issuecomment-144447869 for an example of what the recipes would look like.
