### ISSUE TITLE
bootstrap instances to chef-server

### ISSUE THREAD

**Issue by lcc2207** [chef/chef-provisioning-aws#246]
Is there a way todo this today, I've used the chef_server option and the pem etc all keep using chef-zero

**Comment by christinedraper** [comment]
Either something like:
```
machine "test2" do
  chef_server( :chef_server_url => "http://<server_name>:<port>")
end
```

or 
```
with_chef_server "http://<server_name>:<port>"

machine "test2" do 
...
end
```
should work. If they don't, perhaps you could provide more info on what's in your recipe and the version of chef-provisioning gems you're using (e.g. output from 'gem list chef').

**Comment by tyler-ball** [comment]
We need to add some documentation if users aren't sure how to do this.  But @christinedraper is correct - you should be able to specify the chef_server in either of the ways she suggests.  Can you try that and see if that achieves what you want?
