### ISSUE TITLE
Cannot reference machines by ID in a load_balancer

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#247]
Trying to do the following will not work:

```ruby
load_balancer "test" do
  machines ["test", "i-123456"]
end
```

If there is a machine `"test"`, that will be correctly added to the load balancer.  But because there is no resource `"i-123456"` (a direct identifier) that addition fails.

My theory is that we could update the `aws_instance` resource to expose the `option_names` that would like `AwsInstance` with `machines` via the lookup options.  But that would need to be tested.

**Comment by tyler-ball** [comment]
A potential workaround (I haven't tested this)...

```ruby
machine "my_machine" do
  #id existing_machine.id
  action :nothing
end

load_balancer "elb" do
  machines ["my_machine"]
end
```

In the future if we eventually store the node object "my_machine" on the chef server, this could be unwanted charges for users (nodes cost money).  If users don't want to manage the node with chef their best solution is to have the `i-123456` lookup work.  Either way, if we change the current behavior and start storing Chef objects when the `id` attribute is specified on a resource we should communicate to users that this could cost them money.

**Comment by djapg** [comment]
Great, thanks Tyler! I will definitely try the potential workaround mapping the machine/id, and see if that'll get me by for now.

**Comment by tyler-ball** [comment]
Ugh, I don't think my original suggestion or my workaround will function right now.

My original suggestion won't work because the `machines` attribute is passed into the AWS driver method as `machine_specs` from https://github.com/chef/chef-provisioning/blob/master/lib/chef/provider/load_balancer.rb#L31.  So `lookup_options` isn't even called on them.

For the same reason, my workaround won't work either.

We could come up with a suuuuuuuper janky workaround where we pass any machines that cannot be looked up as specs into the AWS driver and then have special case handling there, but thats pretty smelly.  I would rather just introduce a fully supported `aws_load_balancer` resource that doesn't depend on any of the shared resources/providers in chef-provisioning.

**Comment by gmiranda23** [comment]
+1 on splitting out aws_load_balancer from shared resources/providers.  We've hit usability issues because of that in #27 and #242 (maybe others I'm missing).
