### ISSUE TITLE
Investigate AWS::EC2::Errors::InvalidVpcID::NotFound

### ISSUE THREAD

**Issue by metadave** [chef/chef-provisioning-aws#251]
Investigate additional issues from  https://github.com/chef/chef-provisioning-aws/pull/245#event-346956394

test recipe:
```
aws_vpc VPC do
   cidr_block '10.0.0.0/24'
   internet_gateway true
   main_routes '0.0.0.0/0' => :internet_gateway
   enable_dns_hostnames true
   enable_dns_support true
end
```

cc @Jimflip

**Comment by tyler-ball** [comment]
I'm pretty sure this is because we need some retry logic on the tagging.  This may be fixed by https://github.com/chef/chef-provisioning-aws/pull/299

**Comment by tyler-ball** [comment]
Going to close this since the tagging support was just merged to master!
