### ISSUE TITLE
Ability to tag machines

### ISSUE THREAD

**Issue by afiune** [chef/chef-provisioning-aws#252]
As a user I need to be able to `tag` my machines through the `machine` resource so when my cleaning process in AWS happen, my machine doesn't get deleted. 

I would like to be able to do:
```ruby
machine 'pikachu' do
  aws_tag 'pokemon'
end
```

**Comment by RogerJoys** [comment]
Have you tried aws_tags property of machine_options ?

**Comment by tyler-ball** [comment]
@RogerJoys is correct - see https://github.com/chef/chef-provisioning-aws#base-resources
