### ISSUE TITLE
aws_launch_configuration doesn't respect key_name

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-provisioning-aws#255]
I can't figure out how to pass `key_name` to `aws_launch_configuration`.   It's not an available attribute, so I'm assuming you have to pass it in via options.   Here's what I'm trying to do:

```ruby
aws_launch_configuration 'irving-windows-launch-configuration' do
  image 'irving-windows-image'
  instance_type 't2.medium'
  options security_groups: 'irving-windows-sg', key_name: 'my-aws-key'
end
```

but the launch configuration gets created with no key:

<img width="1207" alt="screen shot 2015-07-11 at 9 50 28 am" src="https://cloud.githubusercontent.com/assets/1616328/8634561/53932c5e-27b2-11e5-9cd4-40f2182a97f0.png">

**Comment by chasebolt** [comment]
@irvingpop replacing key_name with key_pair should fix it

**Comment by irvingpop** [comment]
@chasebolt thanks!   can I ask how you figured that out?

I'm still scratching my head at this: https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_launch_configuration.rb#L10

and why there's inconsistency between `:key_name` (for machine and machine_image) but `:key_pair` for other things.   how is a user supposed to know when to use which one?

cc: @jkeiser @tyler-ball

**Comment by pburkholder** [comment]
I refer to the AWS SDK for the collection object, http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/AutoScaling/LaunchConfigurationCollection.html, and see that that uses 'key_pair'

**Comment by chasebolt** [comment]
options are passed through to the aws-sdk, which you can find additional parameters to use in the docs. http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/Client.html#create_launch_configuration-instance_method

the aws-sdk uses key_pair for asg and key_name for instances, not sure why as that really is confusing. But you can see the reference in the doc for creating instances. http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#run_instances-instance_method

**Comment by irvingpop** [comment]
thanks @pburkholder  @chasebolt that was hugely helpful!   That pointer to the code made things pretty clear.

**Comment by charlesjohnson** [comment]
Should we add these examples to the docs?

**Comment by pburkholder** [comment]
aws-sdk v2 makes a cleaner distinction between key_pair and key_name.

key_pair objects are needed on object instantiation, and key_name is
read-only method returned the name of the key_pair associated with an
object (instance or launch_config).

I think we should adopt a similar approach in c-p-aws.

P.

On Wednesday, July 15, 2015, Charles Johnson <notifications@github.com>
wrote:

> Should we add these examples to the docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef-provisioning-aws/issues/255#issuecomment-121776315>
> .
>


-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability: Fully available early July....

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by tyler-ball** [comment]
It looks to me like `key_name` is used on both the ASG and Instance creation methods in V2 (which is cleaner).  The only reference I could find to `key_pair` was in actually creating the key pair object.

I'll update the docs now with the caveat that ASG uses `key_pair` instead of `key_name`.
