### ISSUE TITLE
Elastic Load Balancers: SSL works on create, but not update

### ISSUE THREAD

**Issue by danieljimenez** [chef/chef-provisioning-aws#258]
```
    load_balancer "#{env_name}" do
      machines web_machines
      load_balancer_options subnets: subnets,
                            security_groups: [load_balancer_sg],
                            listeners: [{
                                            instance_port: 8080,
                                            protocol: 'HTTP',
                                            instance_protocol: 'HTTP',
                                            port: 80
                                        },
                            {
                                instance_port: 8080,
                                protocol: 'HTTPS',
                                instance_protocol: 'HTTP',
                                port: 443,
                                ssl_certificate_id: "arn:aws:iam::360965486607:server-certificate/cloudfront/foreflight-2015-07-09"
                            }
                            ]
    end
```

This will work the first time, but fail every time after with the error

```
    AWS::Core::OptionGrammar::FormatError
    -------------------------------------
    expected string value for option ssl_certificate_id
```

**Comment by tyler-ball** [comment]
Hey @danieljimenez - can you gist the output from the full stacktrace?

**Comment by danieljimenez** [comment]
Sure, rerunning now. I forget what the exact attribute I used to create the LB w/SSL was, but it wouldn't let me run another run against it after.

**Comment by danieljimenez** [comment]
Actually there isn't much else to it, no stack trace besides the error above and the outputted code.

**Comment by tyler-ball** [comment]
The chef run should have dropped a stacktrace in `.chef/local-mode-cache/cache/chef-stacktrace.out` or the same path under your home directory.  Look near the bottom of the chef run output - it should give the path.

**Comment by danieljimenez** [comment]
Got it, thanks :) 

https://gist.github.com/danieljimenez/ddfbe035853a76984027

**Comment by stevendanna** [comment]
A workaround here is to use the key `server_certificate` rather than `ssl_certificate_id`.  Locally that works for both create and update for me.

The issue with `ssl_certificate_id` on update is here:

https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L257

where we check the `desired_listener[:server_certificate]`.  I was surprised `server_certificate` worked in the listener spec since the API for ELB creation lists ssl_certificate_id, but I assume that the ruby AWS SDK is helping us here.

**Comment by danieljimenez** [comment]
I just tested and indeed this works well, leaving the only parts of ELB not automated the health checks, thanks @stevendanna!!!

**Comment by tyler-ball** [comment]
I'm curious why `server_certificate` is working - it doesn't look like that is a valid param for http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/LoadBalancerCollection.html#create-instance_method

**Comment by stevendanna** [comment]
I believe it is a method on listener.

**Comment by tyler-ball** [comment]
https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/elb/listener_opts.rb#L34-L37

**Comment by tyler-ball** [comment]
@danieljimenez check out https://github.com/chef/chef-provisioning-aws/pull/274 for a resource to manage server certificates.  If you have time, would you review that and make sure it will fit your use case?
