### ISSUE TITLE
when an audit-mode recipe is part of the node's specified run_list, provisioning run stack traces

### ISSUE THREAD

**Issue by ricardolupo** [chef/chef-provisioning-aws#259]
When I have an audit-mode recipe as part of my run_list in a provisioning recipe, the provisioning run stack traces with a generic 

The audit-mode recipe is designed to intentionally fail audits, but as of chef-client 12.4.1, audit failures are not supposed to break a chef-client run; merely report that there are audit items that need remediation.

**Comment by galenemery** [comment]
Note that this failure does not exist when you run chef-client manually.  The provisioned node will report back to Chef Server and analytics that it failed audit, but not converge.

However the provisioner node fails and does not continue its recipes.

**Comment by ricardolupo** [comment]
closing and reopening in correct repo
