### ISSUE TITLE
Cannot create security groups when creating an ec2 instance. 

### ISSUE THREAD

**Issue by ricardolupo** [chef/chef-provisioning-aws#271]
Chef Development Kit Version: 0.7.0.rc.2
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.1
remrlupo01:cloud_framework rlupo$ chef gem list | grep provisioning
chef-provisioning (1.2.1, 1.2.0)
chef-provisioning-aws (1.3.0, 1.2.1, 1.1.1)

Full output of provisioning run: https://gist.github.com/902a38c47a25aefb6885
stacktrace: https://gist.github.com/529aac7cb26afd5b8dbc

================================================================================
    Error executing action `create` on resource 'aws_security_group[rlupo_aws_sa-winrm-sg]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `ec2' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In /Users/rlupo/.chef/cache/cookbooks/aws_deploy/recipes/aws-deploy-win.rb

     13: aws_security_group "#{name}-winrm-sg" do
     14: 	action :create
     15:   inbound_rules '0.0.0.0/0' => [ 5985, 5986 ]
     16: end
     17:

**Comment by pburkholder** [comment]
Do other chef-provisioning-aws recipes work for you?

On Fri, Jul 31, 2015 at 1:57 PM, Ricardo Lupo <notifications@github.com>
wrote:

> Chef Development Kit Version: 0.7.0.rc.2
> chef-client version: 12.4.1
> berks version: 3.2.4
> kitchen version: 1.4.1
> remrlupo01:cloud_framework rlupo$ chef gem list | grep provisioning
> chef-provisioning (1.2.1, 1.2.0)
> chef-provisioning-aws (1.3.0, 1.2.1, 1.1.1)
>
> Full output of provisioning run:
> https://gist.github.com/902a38c47a25aefb6885
> stacktrace: https://gist.github.com/529aac7cb26afd5b8dbc
>
> Error executing action `create` on resource 'aws_security_group[rlupo_aws_sa-winrm-sg]'
> ================================================================================
>
> NoMethodError
> -------------
> undefined method `ec2' for nil:NilClass
>
> Resource Declaration:
> ---------------------
> # In /Users/rlupo/.chef/cache/cookbooks/aws_deploy/recipes/aws-deploy-win.rb
>
>  13: aws_security_group "#{name}-winrm-sg" do
>  14:    action :create
>  15:   inbound_rules '0.0.0.0/0' => [ 5985, 5986 ]
>  16: end
>  17:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef-provisioning-aws/issues/271>.
>



-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability: 4 August - 27 August -- OOO for Vacation/Conferences

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by ricardolupo** [comment]
@pburkholder this recipe was working last week but now gives me the error trying to create the sg. If I remove the aws_security_group resource, create the SG manually, assign it in the recipe and run it, it converges successfully

**Comment by ricardolupo** [comment]
Recipes located in: https://github.com/chef-cft/cloud_framework/blob/master/cookbooks/aws_deploy/recipes

Provision recipe:
https://github.com/chef-cft/cloud_framework/blob/master/cookbooks/aws_deploy/recipes/aws-deploy.rb
Destroy recipe:
https://github.com/chef-cft/cloud_framework/blob/master/cookbooks/aws_deploy/recipes/aws-destroy.rb

**Comment by ricardolupo** [comment]
Closing issue. User error in recipes.

**Comment by ff-jantreassian** [comment]
@ricardolupo what was the issue?
