### ISSUE TITLE
Should you get t1.micro instances by default?

### ISSUE THREAD

**Issue by tpetchel** [chef/chef-provisioning-aws#29]
By default, a `machine` resource gives you an Ubuntu ami-f1ce8bc1 **m1.small** instance. Would it be better to make this a **t1.micro**, so folks can take advantange of free tier usage?

If the user is using the default, she may likely be just experimenting with gettings things off the ground, and may not benefit from an m1.small, and may not want to spend the extra money on it.

**Comment by jkeiser** [comment]
Yes.  t1.micro should be the default.  I'm super surprised it isn't.

**Comment by christinedraper** [comment]
Possibly it should be t2.micro instead 
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts_micro_instances.html

**Comment by robcoward** [comment]
A couple of caveats with defaulting to t2.micro - if you see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html t2 instances can only be launched in a VPC - ec2-classic is not supported. They also force you to use HVM ami's.

**Comment by jkeiser** [comment]
Is there much cost difference? I can imagine defaulting everything to vpc with public ip or some such ...


Apologies for asking something I could do with a calculator and some research, but I'm out this week and shirt on research cycles :)

**Comment by christinedraper** [comment]
t2.micro is cheaper than t1.micro in most regions, and is what Amazon advertize as being in their free tier.

**Comment by dblessing** [comment]
t1 instances are considered 'previous generation' and will likely go away altogether at some point.

**Comment by tyler-ball** [comment]
Closing because master has `t2.micro` as default
