### ISSUE TITLE
Provisoner's IAM roles are not used

### ISSUE THREAD

**Issue by Fodoj** [chef/chef-provisioning-aws#292]
Currently there is no way to avoid specifying AWS credentials. I am running provisioner node on EC2 instance, this insance has IAM role that allows it to create AWS resources. Using credentials on EC2 is a bad practice and IAM roles must always be used instead of them.

Normal workflow (that is already built into aws-sdk) is this:

1. Check if user hardcoded credentials
2. If not, try to find them in environment variables
3. If not then check if current machine is EC2 and has instance profile
4. If wrong permissions or not EC2 => explode with permissions error.

Currently chef-provisioning-aws supports steps 1 and 2. Easies way to implement whole flow is to remove validation for credentials presence.

**Comment by thommay** [comment]
Hi @Fodoj ; you can use IAM credentials:
```
with_driver('aws:IAM:us-west-1', aws_credentials: { 'IAM' => iam.credentials})
```

**Comment by Fodoj** [comment]
@thommay awesomem thanks! couldn't get it from source code, by mistake

**Comment by Fodoj** [comment]
Actually, it says `No resource, method, or local variable named `iam' for `Chef::Recipe "_aws_driver"'` :(

**Comment by Fodoj** [comment]
Full working example:

```
iam = AWS::Core::CredentialProviders::EC2Provider.new
with_driver('aws:IAM:us-west-1', aws_credentials: { 'IAM' => iam.credentials})
```

**Comment by Fodoj** [comment]
Ok, after thinking about it for a while - this solution looks like a hack. If I add this `iam =` then I can't use it locally, from workstation. Switch from IAM to local credentials should happen seamlessly, like by default in aws sdk.

**Comment by tyler-ball** [comment]
@fodoj Switching to the AWS SDK V2 should fix this issue.  I have a branch in progress which uses the SDK V2 for the `machine` resource at https://github.com/chef/chef-provisioning-aws/pull/293 - if you could try this code out and see if it correctly loads the IAM profile, I would appreciate it!

As a workaround you could add a `begin`/`rescue` block around the [previous code](https://github.com/chef/chef-provisioning-aws/issues/292#issuecomment-132255130) pasted and don't use IAM if it is unable to load it (I think there is an AWS specific exception if this happens).

**Comment by Fodoj** [comment]
begin/rescue is exactly what I did for now :-) waiting for aws sdk 2 support then, thanks 



Best regards,
Kirill Shirinkin

**Comment by tyler-ball** [comment]
I'm going to close this as #293 is in master, we'll be rolling the V2 updates to more resources over time, and we have a workaround documented here.  @Fodoj feel free to re-open if you don't think this is an appropriate close!

**Comment by Fodoj** [comment]
@tyler-ball no problem! Here is a full work around for those who find this issue before sdk v2 support release:

```
iam = AWS::Core::CredentialProviders::EC2Provider.new

begin
  with_driver "aws:IAM:eu-west-1", aws_credentials: { 'IAM' => iam.credentials }
rescue  AWS::Errors::MissingCredentialsError
  with_driver "aws::eu-west-1"
end
```

**Comment by tyler-ball** [comment]
@Fodoj thanks for the summary docs!
