### ISSUE TITLE
ERROR: :aws_instance_profile bootstrap option expects a hash (between 1.3.1 and master)

### ISSUE THREAD

**Issue by keen99** [chef/chef-provisioning-aws#309]
Running master for debugging another unrelated issue, ran into this.   

````
[2015-09-02T16:02:57-04:00] ERROR: machine[iam-profile-test] (chef-metal::iam-profile-test line 16) had an error: ArgumentError: expected params[:iam_instance_profile] to be a hash
````

with ````gem 'chef-provisioning-aws', '1.3.1'````
this works fine.

with ````gem 'chef-provisioning-aws', github: 'chef/chef-provisioning-aws'````

it breaks.

note:  machine must go from :destroy to :ready/converge to see the error.  an already :ready machine won't trigger this.

reviewing https://github.com/chef/chef-provisioning-aws/compare/v1.3.1...master looks like there's a fair scope of change around this, but I can't wrap my head around it at quick scan. :)

full log output, Gemfile.lock, and stacktrace here: https://gist.github.com/keen99/3d6b788662c3940a2211

recipe:
````
require 'chef/provisioning'

require 'chef/provisioning/aws_driver'

with_driver 'aws'

with_machine_options({
  :bootstrap_options => {
    :instance_type => 't2.micro',
    :iam_instance_profile => "chefprov_profile",
   },
})


machine 'iam-profile-test' do
#  action :converge
  action :ready
#   action :destroy
end
````

**Comment by keen99** [comment]
So this seems to be the new required format (and at first glance it works with 1.3.1 and 1.4.0.dev.1 both):
````
with_machine_options({
  :bootstrap_options => {
    :instance_type => 't2.micro',
    :iam_instance_profile => { :name => "chefprov_profile", },
   },
})
````

leaving this open since it seems to be a potential breaking change for some folks, if they're not passing a hash, and might need to be documented or fixed...

**Comment by tyler-ball** [comment]
SDK V1 create - http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EC2/Client.html#run_instances-instance_method

SDK V2 create - http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#run_instances-instance_method

The biggest change around this I can think of is that we changed from the V1 SDK to the V2 SDK for machines.  But a hash was expected in both V1 and V2.  Looking some more...

**Comment by tyler-ball** [comment]
Ah, found it - http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EC2/InstanceCollection.html#create-instance_method

The V1 `InstanceCollection` accepted it as a string instead of a hash.  Looks like the 1.x branch of chef-provisioning-aws needs to convert a provided string to a hash and issue a deprecation message until 2.0 comes out.

**Comment by keen99** [comment]
thanks for tracking it down.   I seem to recall most the examples I could find out there used a string, which is why it was kicking my tail. :)
