### ISSUE TITLE
machine_image recreation fails randomly

### ISSUE THREAD

**Issue by Fodoj** [chef/chef-provisioning-aws#311]
Simple code:

```ruby
machine_image "my-ami" do
  recipe "my-recipe"
  action [:destroy, :create]
end
```

Works in 50% of cases. In other 50 returns:

```
[2015-09-04T14:18:18+00:00] ERROR: machine_image[my-ami] (fyber-environments::_rebuild_base_images line 3) had an error: AWS::Core::Resource::NotFound: aws_image[base-ami] (ami-15745262) (basic_chef_client::block line 451) had an error: AWS::Core::Resource::NotFound: unable to find the instance
```

Is it related to the fact that AMIs always have `From-instance` tag that is never flushed and thus chef-provisioning-aws tries to destroy image from this tag even though it doesn't exist already?

**Comment by tyler-ball** [comment]
@Fodoj Hmm, I'm not sure.  Would you mind including the full stack trace from when you see this happen?  I wonder if this is related to https://github.com/chef/chef-provisioning-aws/issues/256 or https://github.com/chef/chef-provisioning-aws/issues/254

**Comment by tyler-ball** [comment]
Hey @Fodoj - I'm going to close this since there wasn't a response.  Please re-open if you are able to repro or get a stack trace!

**Comment by Fodoj** [comment]
@tyler-ball I finally had time to debug and fix it. Please see a PR #357
