### ISSUE TITLE
Unable to create ec2 instance with multiple IPs

### ISSUE THREAD

**Issue by tonyflint** [chef/chef-provisioning-aws#322]
I'm attempting to create a machine resource which has mutliple IP addresses (ideally associated with one network interface). Here's the provisioning code I'm using:

```
# multip.rb -- create instance with multiple IPs
require 'chef/provisioning'
require 'chef/provisioning/aws_driver'
with_driver 'aws'

machine 'multi' do
  machine_options ({
      bootstrap_options: {
        key_name:                     'foo',
        instance_type:                'm4.large',
        image_id:                     'ami-foo',
        subnet:                       'subnet-foo',
        security_group_ids:           'sg-foo',
        placement: {
            availability_zone:        'us-west-2b',
          },
        network_interfaces: [
          {
            network_interface_id: "eth0",
            device_index: 0,
            subnet_id:  'subnet-foo',
            description: "String",
            private_ip_address: "foo.foo.foo.primary",
            delete_on_termination: false,
            private_ip_addresses: [
              {
                private_ip_address: "foo.foo.foo.secondary", # required
                primary: false,
              },
            ],
            secondary_private_ip_address_count: 1,
            associate_public_ip_address: false,
          },
        ],
      },
    })
end
```

This appears to conform to the [EC2 create_instances-instance_method docs](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#create_instances-instance_method), yet running it fails:

```
$ chef-client -z multip.rb
[2015-09-15T12:32:19-07:00] ERROR: machine[multi] (@recipe_files::/home/tflint/git/chef-server-bootstrap/provisioning-scripts/multip.rb line 5) had an error: Chef::Exceptions::ValidationFailed: Option name must be a kind of String!  You passed {:network_interface_id=>"eth0", :device_index=>0, :subnet_id=>"subnet-2e1e2846", :description=>"String", :private_ip_address=>"10.135.83.84", :delete_on_termination=>false, :private_ip_addresses=>[{:private_ip_address=>"10.135.83.85", :primary=>false}], :secondary_private_ip_address_count=>1, :associate_public_ip_address=>false}.
```

Am I doing something wrong here?

**Comment by tyler-ball** [comment]
@tonyflint I'm pretty sure I know what is going on here - the `lookup_options` for `aws_network_interface` assumes that `network_interfaces` is going to be the name of an `aws_network_interface` resource, thus the error you see.

To make sure I'm right, can you include the full stacktrace from your error?

**Comment by tonyflint** [comment]
Thanks for the quick response. Here's [a gist](https://gist.github.com/tonyflint/d65fbffe147ddb56199f) of the output.

**Comment by tyler-ball** [comment]
@tonyflint I don't think you're doing it wrong - we have claimed that `bootstrap_options` should respect the hash from the `create_instances` method you linked.  

We have a `aws_network_interface` resource, but now that we have updated to the V2 SDK I'm not certain that the lookup magic will link/unlink it to a machine appropriately.

You're free to try creating that resource and seeing if you can assign it two IP addresses.

Eventually, something like the following should work (but I'm not sure it does now):

```ruby
aws_network_interface "foo" do
  # specify options for multiple private IPs
end

machine "my_machine" do
  machine_options bootstrap_options: {
    network_interfaces: ["foo"],
    #...
  }
end
```

Making sure that works is probably another issue after solving this one.

**Comment by tyler-ball** [comment]
Okay, I have a PR incoming for this fix.  Your example from the original comment should still work except for one issue - you cannot specify both `private_ip_addresses` and `secondary_private_ip_address_count`.  AWS raises an error in this case.  But you can specify both `private_ip_address` and `private_ip_addresses` like you show in your example.
