### ISSUE TITLE
 No resource or method named 'aws_rds_instance' for 'Chef::Recipe "test-recipe"'

### ISSUE THREAD

**Issue by aldofunes** [chef/chef-provisioning-aws#336]
This is my setup:
```
$ chef -v

Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
```
As of September 2015, the ```aws_rds_instance``` does not work properly. It throws an error as follows:
```
ERROR: No resource or method named `aws_rds_instance' for `Chef::Recipe "recipe-name"'
```
My recipe is the following:
```ruby
aws_rds_instance "test-rds" do
  engine "mysql"
  publicly_accessible false
  db_instance_class "db.t1.medium"
  master_username "adminuser"
  master_user_password "secretsecret" # 2x security
  multi_az true
  additional_options(
    allocated_storage: 32,
    db_security_groups: ["default"],
    db_subnet_group_name: "default",
    backup_retention_period: 15,
    tags: [name: "test-rds"],
    storage_type: "gp2"
  )
end
```
It seems to me that the chef-provisioning-aws has become incompatible with chef. It is the first time I try to create an RDS with chef though, so I cannot verify that it has worked in the past.

**Comment by tyler-ball** [comment]
Hey @aldofunes - do you have the necessary `require 'chef/provisioning/aws_driver' and `with_driver` line at the top of your recipe?  Just making sure.

What if you do `chef gem list | grep chef-provisioning`?  `aws_rds_instance` wasn't introduced until chef-provisioning-aws 1.4.0.  If you don't have 1.4.0 installed you can do it with `chef gem install chef-provisioning -v 1.4.0 && chef gem install chef-provisioning-aws -v 1.4.0`

**Comment by tyler-ball** [comment]
Hey @aldofunes I haven't heard back from you so I'm going to go ahead and close this.  Please re-open if you are still having issues!
