### ISSUE TITLE
support winrm over https transport

### ISSUE THREAD

**Issue by hh** [chef/chef-provisioning-aws#348]

**Comment by hh** [comment]
#354 is a functioning spike for this, feedback welcome

**Comment by hh** [comment]
I've been using this function spike for a while. Can I get some feedback?
Cheers,
-chris

**Comment by tyler-ball** [comment]
@hh I _think_ the logic in #354 LGTM - it needs a rebase and some cleanup.  If you can do that I'll give it another review!

**Comment by hh** [comment]
It's been a long road, but I think we have thing working now.

**Comment by hh** [comment]
Updated #441
