### ISSUE TITLE
aws_eip_address create action breaks without public_ip attribute

### ISSUE THREAD

**Issue by josb-mi** [chef/chef-provisioning-aws#366]
aws_eip_address 'addr' do
      machine 'myhost'
    end

fails with

```
IPAddr::AddressFamilyError: address family must be specified
/opt/chefdk/embedded/lib/ruby/2.1.0/ipaddr.rb:475:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/resource/aws_eip_address.rb:28:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/resource/aws_eip_address.rb:28:in `block in <class:AwsEipAddress>'
```
Trivial fix:
```
--- a/lib/chef/resource/aws_eip_address.rb
+++ b/lib/chef/resource/aws_eip_address.rb
@@ -25,7 +25,7 @@ class Chef::Resource::AwsEipAddress < Chef::Provisioning::AWSDriver::AWSResource
   # end
   # ```
   #
-  attribute :public_ip, kind_of: String, aws_id_attribute: true, coerce: proc { |v| IPAddr.new(v); v },
+  attribute :public_ip, kind_of: String, aws_id_attribute: true, coerce: proc { |v| IPAddr.new(v) rescue v },
     default: lazy {
       begin
         IPAddr.new(name)
```

**Comment by josb-mi** [comment]
I'll add that I find the original code puzzling. If ```IPAddr.new(v)``` in the proc has no side-effects, what's the point of invoking it? In the original, the proc will return ```v``` anyway. Same for ```name``` a few lines down.

**Comment by jwilf** [comment]
I just ran into this bug as well. Is there any workaround that doesn't involve forking the gem?

**Comment by josb-mi** [comment]
Not that I am aware of. Since it's a one-line change, I just edited my local copy for now :-)

**Comment by randomcamel** [comment]
Since `IPAddr.new` throws an exception for a malformed address, I'd guess it's being used as validation.

@josb-mi @jwilf:

1. What's the value being fed into IPAddr that's raising the exception?
1. What version of Ruby are you using?

**Comment by josb-mi** [comment]
@randomcamel:

1. value is nil, since we don't specify public_ip on the resource.
2. 2.1.6p336

**Comment by josb-mi** [comment]
What else is needed to have this land so I don't have to patch my ChefDK? Thanks!

**Comment by ErikDahlinghaus** [comment]
I'd like to bump this as well.
