### ISSUE TITLE
unexpected value at params[:ssh_user] in with_machine_options, add_machine_options , machine_options 

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-aws#409]
I have initially builded an instance with default username and specified ubuntu user in knife.rb and successfully created ubuntu instance but after that I thought of building an RHEL-7 instance so I have removed :ssh_user in knife.rb and tried to create an instance it has created an instance and during the running of chef-recipe it is trying to connect with ubuntu and failing to connect as RHEL don't have ubuntu  user. I have specified :ssh_user in knife.rb and tried but the same result is happening and kept :ssh_user in  with_machine_options, add_machine_options , machine_options separately in machine resource and found the following error

**Comment by christinedraper** [comment]
I assume this is the problem you pinged me about on my blog https://christinemdraper.wordpress.com/2015/01/31/deploying-a-multi-node-application-to-aws-using-chef-provisioning/#comment-599

Can you post the relevant pieces of your recipe?

**Comment by phanikumar1210** [comment]
Thanks for your response I have resolved this issue with few modifications to machine_options. I would like to know why with_machine_options, add_machine_options , options are completely not working at all inside a machine resource are they deprecated. I have used the below code. 

machine "#{i}" do
with_machine_options :ssh_username => 'ec2-user',
  :bootstrap_options => {
  :instance_type => 't2.micro',
  :associate_public_ip_address => true,
  :image_id => "ami-dc1c2b8e"
}
recipe 'java'
recipe 'apache_latest'
end
end

**Comment by christinedraper** [comment]
with_machine_options is intended to set defaults across machine instances (all of the "with_xxx" functions do this). add_machine_options adds extra options into the defaults for a specific machine. For example, I just checked the following works:

```
with_machine_options(bootstrap_options: {
    key_name: 'test1_aws'
  })

machine 'test' do
 add_machine_options bootstrap_options: {
    associate_public_ip_address: true
  }
end
```

I haven't met a plain 'options' option.

**Comment by phanikumar1210** [comment]
Hi Christine Draper,

Thanks for the information. I think this information may help me but in any
case either of both should work in specifying ssh_user right but why  they
got failed I have tried specifying them outside the machine resource as
well.Could you please help me in getting a bit more clarification whether
or not such property is available with it now.

**Comment by christinedraper** [comment]
Try:
```
with_machine_options :ssh_username => 'ec2-user',
:bootstrap_options => {
:instance_type => 't2.micro',
:associate_public_ip_address => true,
:image_id => "ami-dc1c2b8e"
}

machine "#{i}" do
  recipe 'java'
  recipe 'apache_latest'
end

```
