### ISSUE TITLE
unable to start new instance using aws_auto_scale

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-aws#411]
Hi, I want to create an auto scaling on already build machine so I have executed the below code 

machine_image 'image' do
        add_machine_options :ssh_username => 'ubuntu',
          :bootstrap_options => {
          :instance_type => 't1.micro',
          :associate_public_ip_address => true,
          :image_id => "ami-e8f1c1ba"
        }
        recipe 'java'
        recipe 'apache_latest'
end
machine 'web1' do
        from_image 'image'
end
machine 'web2' do
        from_image 'image'
end
aws_launch_configuration 'config' do
        image 'image'
        instance_type 't1.micro'
end
aws_auto_scaling_group 'auto-scaling-group-name' do
    availability_zones ['ap-southeast-1a']
    desired_capacity 2
    min_size 1
    max_size 2
    launch_configuration 'config'
end

I am getting the following error "an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2". What my correct requirement is I need an instance with recipe java and apache on it by default. Can anyone help me resolving this.

**Comment by christinedraper** [comment]
You don't need to create the two web machines... the autoscaling group will create instances itself, to meet the desired capacity.

**Comment by phanikumar1210** [comment]
Hi christinedraper,

Thanks for your response. I have removed code for creating instances and checked them once again but still I was unable to implement auto scaling as it is trying to create instance to reach the requirement but it is failing do to some errors like

a user request created an AutoScalingGroup changing the desired capacity from 0 to 2. At 2015-12-08T17:17:59Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2

when no instance is created at all and

an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2

when one instance is created. My main requirement is to create instances with specific recipes java and apache_latest installed on it.

**Comment by christinedraper** [comment]
It sounds like you are getting a message that suggests instances are being started to meet the desired capacity, but this is randomly failing - is that true?

If so, is the Chef run actually aborting? Can you post the stacktrace?

**Comment by phanikumar1210** [comment]
No Chef-run is executing successfully but the auto-scaling is not able to start new instance. It has tried more than 15 times with the similar failure.

**Comment by christinedraper** [comment]
So it seems like something outside of Chef is a problem. This might help diagnose what is going on....

http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/CHAP_Troubleshooting.html#RetrievingErrors

**Comment by phanikumar1210** [comment]
Thank you christindedraper, I found the iisue and resolved it.
