### ISSUE TITLE
Unable to connect and ping public IP on AWS

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-aws#415]
I have configured my workstation with AWS and it is able to create an instance on the Amazon AWS and assign a public IP to it but the chef-client run is failing to run my recipe on the AWS as it is unable to connect to the instance created and I have tried to ping the Public IP and Public DNS from my system but it is unable to respond. At the same time I was able to create and ping and run instance using AWS GUI. Can anyone please assist me in sorting out this issue.

**Comment by christinedraper** [comment]
Check that you have enabled SSH access from the IP address where you are running the chef-client. 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by phanikumar1210** [comment]
Hi christinedraper,
I have worked with another credentials on the same chef-client for another aws account it worked fine and later I have again configured it with new credentials from then I am facing the problem. All the inbound and outbound traffic is enabled on that Instance security group. The public IP or public DNS is not even getting pinged.
