### ISSUE TITLE
Add Health Checks to loadbalancers

### ISSUE THREAD

**Issue by cwndrws** [chef/chef-provisioning-aws#420]
It doesn't seem like there's a way to configure a health check. I would like to be able to configure a health check and then attach it to a load balancer, or just declare a health check on load balancer creation.

**Comment by rgeddis** [comment]
Not sure if this exactly what you are looking but you can configure the health check in the load_balancer_options, for example

{code}                                                                                                                                                                                        load_balancer_options lazy {                                                                                                                                                                                        
  {                                                                                                                                                                                                                 
    listeners: [{                                                                                                                                                                                                   
      port: 80,                                                                                                                                                                                                     
      protocol: :http,                                                                                                                                                                                              
      instance_port: 80,                                                                                                                                                                                            
      instance_protocol: :http                                                                                                                                                                                      
    }, {                                                                                                                                                                                                            
      port: 443,                                                                                                                                                                                                    
      protocol: :https,                                                                                                                                                                                             
      instance_port: 443,                                                                                                                                                                                           
      instance_protocol: :https                                                                                                                                                                    
    }],                                                                                                                                                                                                             
    health_check: {                                                                                                                                                                                                 
      healthy_threshold: 2,                                                                                                                                                                                         
      unhealthy_threshold: 4,                                                                                                                                                                                       
      interval: 12,                                                                                                                                                                                                 
      timeout: 5,                                                                                                                                                                                                   
      target: 'HTTPS:443/_status'                                                                                                                                                                                   
    },                                                                                                                                                                                                              
    scheme: 'internet-facing',                                                                                                                                                                                      
    subnets: lb_subnet,                                                                                                                                                                                             
    security_groups: [                                                                                                                                                                                              
      security_group.aws_object.id                                                                                                                                                                                   
    ]                                                                                                                                                                                                               
  }                                                                                                                                                                                                                 
}                                                                                                                                                                                   
{code}

**Comment by cwandrews** [comment]
@rgeddis where are you seeing this in the docs? I don't see it in the docs for this repo nor in the [aws docs](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#create_load_balancer-instance_method) that describe the load balancer creation options.

**Comment by lskillen** [comment]
This answer shouldn't be considered canonical unless it comes from a developer, but the short answer is "a pinch of magic" - The actual call made is `configure_health_check` which you can see [here](https://github.com/chef/chef-provisioning-aws/blob/70578c491e1f83e24245e0930504ffdd4f118643/lib/chef/provisioning/aws_driver/driver.rb#L383-L394).  So basically the AWS chef provisioning resource is doing some of the heavy lifting for you by taking the `health_check` subsection of the `load_balancer_options` hash out and applying it via `configure_health_check` (idempotently, if the desired state is different).  It's probably a good idea to have a look at the spec tests to get other examples of resource usage, such as the [load balancer specs](https://github.com/chef/chef-provisioning-aws/blob/master/spec/integration/load_balancer_spec.rb).  HTH!

**Comment by cwandrews** [comment]
Yes that helps, but it should definitely be included in the docs.
