### ISSUE TITLE
Improper flow of security group delete action

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-aws#422]
Hi, I would like to destroy security group of aws using aws_security_group and it is executing fine bute but when ever I go for a second chef-client run it is showing me error specifying that the security group doesn't exist and terminating the chef-client run. I if someone could help how can Iet the chef-client run without ignore_failure.

**Comment by christinedraper** [comment]
@phanikumar1210  can you post the relevant recipe and the error message/first part of stacktrace?

I tried to reproduce using the following (with chef-provisioning-aws 1.7.0), but was able to rerun multiple times with no error.
```
require 'chef/provisioning/aws_driver'
with_driver 'aws'

aws_vpc 'test-vpc' do
  cidr_block '10.0.0.0/24'
end

aws_security_group 'test-sg' do
  vpc 'test-vpc'
  action :delete
end
```

**Comment by phanikumar1210** [comment]
================================================================================
    Error executing action `destroy` on resource 'aws_security_group[default_2]'
    ================================================================================
    
    RuntimeError
    ------------
    Chef::Resource::AwsVpc[test-vpc] does not exist!
    
    Resource Declaration:

The above is what the error what I am getting.

**Comment by christinedraper** [comment]
Are you deleting the VPC as well? If you have the following:
```
require 'chef/provisioning/aws_driver'
with_driver 'aws'

aws_vpc 'test-vpc' do
  cidr_block '10.0.0.0/24'
  action :delete
end

aws_security_group 'test-sg' do
  vpc 'test-vpc'
  action :delete
end
```
It will fail when it gets to the security group, because the specified VPC no longer exists. You'd either need to delete the security group first, or just delete the VPC (which will also delete the security group).

**Comment by phanikumar1210** [comment]
Thank you.
