### ISSUE TITLE
When creating security-groups, the name should not be case-sensitive

### ISSUE THREAD

**Issue by dreamnite** [chef/chef-provisioning-aws#452]
If I have a security group that was previously created with the name "Abc" and try:
```ruby
aws_security_group "ABC" do 
...
end
```
It will fail with an error "AWS::EC2::Errors::InvalidGroup::Duplicate". Since Amazon is treating the item as case-insensitive, the driver should as well.

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-provisioning-aws/issues/457

**Comment by tyler-ball** [comment]
Actually, I'm reverting the fix I merged in #457. Aws has no case-insensitive way we can query security groups, so there is no way for us to tell from a resource named `"ABC"` whether there is a different case of that same security group that already exists. We could try every permutation on casing, but that is a bad idea.

Thats also the same error that you get if you try to create `"ABC"` then `"Abc"` through the AWS console. So I'm unfortunately going to close this as won't fix.
