### ISSUE TITLE
WinRM::WinRMAuthorizationError

### ISSUE THREAD

**Issue by dushyant28** [chef/chef-provisioning-aws#456]
I am trying to test chef provisioning for provisioning windows boxes on AWS.

my recipe looks like: 

chef_gem 'chef-provisioning-aws' do
  options('--no-document --no-user-install --install-dir /opt/chefdk/embedded/lib/ruby/gems/2.1.0')
  compile_time true if respond_to?(:compile_time)
end

require 'chef/provisioning'
require 'chef/provisioning/aws_driver'

with_driver(
   node['aws-provisioning']['aws']['iam_creds_region']
)

machine 'windows_test_01' do
  machine_options( 
    is_windows: node['aws-provisioning']['aws']['is_windows'],
    transport_address_location: :private_ip,
    winrm_username: node['aws-provisioning']['aws']['winrm_username'],
    bootstrap_options: {
      key_name: node['aws-provisioning']['aws']['key_pair'], 
      image_id: node['aws-provisioning']['aws']['windows_ami-id'],
      security_group_ids: ['sg-e8684c8c'],
      subnet_id: node['aws-provisioning']['aws']['subnet_id']['az1'],
      instance_type: node['aws-provisioning']['aws']['instance_type']
    })
end

I am able to provision the box but winrm connection fails !

WinRM::WinRMAuthorizationError: machine[windows_test_01] (provision::demo line 13) had an error: WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError

Do i need any additional setting for this to work with windows ? Kindly help

Regards,

Dushyant

**Comment by mistroh** [comment]
Hello, Were you able to find a solution to this?  I am experiencing the same issue.  Thank you.

**Comment by dushyant28** [comment]
Yes.. run the "powershell magic" via user data:

options_windows = {
  is_windows: true,
  transport_address_location: :private_ip,
  winrm_username: node['aws-provisioning']['username']['_windows'],
  aws_tags: { 'UAI' => 'UAI2000169' },
  bootstrap_options: {
    block_device_mappings: [
      {
        device_name: '/dev/sda1',
        ebs: {
          volume_size: 85,
          delete_on_termination: true,
          volume_type: 'gp2', # accepts standard, io1, gp2
        }
      }
    ],
    key_name: node['aws-provisioning']['key_pair'],
    image_id: node['aws-provisioning']['ami_id']['windows'],
    security_group_ids: ["#{node['aws-provisioning']['stack_name']}_sg", node['aws-provisioning']['security_groups']['shared_security']],
    subnet_id: node['aws-provisioning']['subnet_id']['az1'],
    instance_type: node['aws-provisioning']['instance_type']['windows'],
    user_data: <<-EOF
      <powershell>
        Enable-PSRemoting -Force -SkipNetworkProfileCheck
        & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
        & winrm.cmd set winrm/config/winrs "'@{MaxMemoryPerShellMB=1024}' ">> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $logfile
        & winrm.cmd set winrm/config/service/auth '@{Basic="true"}' >> $logfile
        & winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}' >> $logfile
        & winrm.cmd set winrm/config/winrs "'@{MaxMemoryPerShellMB=1024}' ">> $logfile
        & netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" profile=public protocol=tcp localport=5985 remoteip=localsubnet new remoteip=any  >> $logfile
        & netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow  >> $logfile
        & net stop winrm
        & net start winrm
      </powershell>
    EOF
  }
}
machine 'windows_test' do
    machine_options options_windows
end

**Comment by mistroh** [comment]
Thank you for the reply and the assistance.  I've tried what you've suggested, and I can confirm that I have WinRM enabled and configured on the instance, as I can connect to WinRm outside of Chef.  However, I still get the WinRM Authorization errors.  Do you have any other ideas or thoughts I could check to see why Chef can't authenticate?  Thanks

**Comment by dushyant28** [comment]
Do you have the correct key in place on the provisioning node ?

Chef would connect using this key.

**Comment by mistroh** [comment]
Good suggestion, thanks.  This is what I have set in my provision.rb recipe:
```
          :key_name => "Chef",   #my pem file is Chef.pem
	  :key_path => "C:\chef\AWSSandbox",  #my provisioning Chef DK workstation is Windows, so this is my path to the folder where the pem file is located
```
Does that look correct?  This is the same pem I use if I were to manually provision the node in AWS.
