### ISSUE TITLE
Option to enable termination protection

### ISSUE THREAD

**Issue by fletchowns** [chef/chef-provisioning-aws#461]
I think it would be a useful feature to have an attribute to easily enable termination protection for an instance created with the machine resource.

**Comment by badmadrad** [comment]
you should be able to use machine bootstrap options and pass the following:

`disable_api_termination: true`

**Comment by fletchowns** [comment]
Sweet! Thanks @badmadrad. I guess I should have seen that from the readme: https://github.com/chef/chef-provisioning-aws/commit/ee9f9df5956ccf7f88c63b7abc23ad3b4a8b3930

Closing this out.
