### ISSUE TITLE
aws_auto_scaling_group TAGs?

### ISSUE THREAD

**Issue by lcc2207** [chef/chef-provisioning-aws#478]
looking at the docs on https://docs.chef.io/provisioning.html#aws-auto-scaling-group

It appears I should be able to use aws_tags to add tags to my ASG but I am getting the following error 

Error:

NoMethodError
-------------
undefined method `aws_tags' for Chef::Resource::AwsAutoScalingGroup

Cookbook Trace:
---------------
.chef/local-mode-cache/cache/cookbooks/test-provision/recipes/default.rb:60:in `block in from_file'
.chef/local-mode-cache/cache/cookbooks/test-provision/recipes/default.rb:53:in `from_file'

Relevant File Content:
----------------------
.chef/local-mode-cache/cache/cookbooks/sensu-provision/recipes/default.rb:

 53:  aws_auto_scaling_group 'test-ASG' do
 54:    desired_capacity 1
 55:    min_size 1
 56:    max_size 2
 57:    options subnets: node['test-provision']['subnets']
 58:    launch_configuration 'test-launch-config'
 59:    load_balancers 'test-elb'
 60>> aws_tags 'Name' => 'test-ASG'
 61:  end

**Comment by tyler-ball** [comment]
Fixed by https://github.com/chef/chef-provisioning-aws/pull/479
