### ISSUE TITLE
aws_security_group doesn't show (up to date) message

### ISSUE THREAD

**Issue by tpetchel** [chef/chef-provisioning-aws#50]
Converge an `aws_security_group` resource multiple times. You'll see something like the following, but not with the "(up to date)" message that's typical of most other resource types.

```
Recipe: web::servers
  * aws_security_group[webserver-ssh] action create
```

**Comment by vinyar** [comment]
seeing this as well with chefdk 4.0

**Comment by tyler-ball** [comment]
Are you still seeing this in the latest ChefDK?  We did some updates to the security groups so they no longer depend on data bags and I'm hoping that fixed this.

**Comment by tyler-ball** [comment]
Closing this since we haven't seen a response in the last week - please re-open if this is still an issue!
