### ISSUE TITLE
aws_rds_instance use wrong iam url

### ISSUE THREAD

**Issue by pulpo** [chef/chef-provisioning-aws#517]
When trying to create a aws_rds_instance, an error is generated because a wrong iam connection is made:

```
    ================================================================================
    Error executing action `create` on resource 'aws_rds_instance[stage-rds-instance]'
    ================================================================================
    
    SocketError
    -----------
    Failed to open TCP connection to iam.us-east-2.amazonaws.com:443 (getaddrinfo: Name or service not known)
```
Amazon's site says IAM has only one endpoint for IAM: https://iam.amazonaws.com.

[AWS Regions and Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html)

**Comment by pulpo** [comment]
endpoints at aws-sdk-core/endpoints.json for v1, when ussing Ohio region are outdated, updating endpoints.json should be the path to solve this, but I'm afraid v1 of awk-sdk (used by chef-provisioning-aws) is no longer under maintenance.

**Comment by tas50** [comment]
We've updated to V2 so this should no longer be an issue.
