### ISSUE TITLE
Allow longer AMI IDs

### ISSUE THREAD

**Issue by chiku** [chef/chef-provisioning-aws#570]
AWS has started to generate AMIs with longer IDs. 
1. https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/
2. https://aws.amazon.com/about-aws/whats-new/2018/03/new-amis-available-for-testing-longer-format-image-ids/
3. https://www.google.co.in/search?q=testlongids&tbm=isch

The existing code rejects AMIs with a long ID.

Please change the following line to allow AMI IDs with 8 or 17 letters.
https://github.com/chef/chef-provisioning-aws/blob/821df69c72df25f744fe879ca32f0bd98a0ec36f/lib/chef/resource/aws_image.rb#L14

**Comment by jjlimepoint** [comment]
https://github.com/chef/chef-provisioning-aws/pull/571 fixes this

**Comment by tas50** [comment]
Fixed thanks to @jjlimepoint
