### ISSUE TITLE
Provisioning only creates t1.micros

### ISSUE THREAD

**Issue by scarolan** [chef/chef-provisioning-aws#63]
I specified an m3.medium in my config, and chef provisioning reports back that is what it's creating:

```
    - creating machine backend1.example.local on fog:AWS:410980185594:us-west-2
    -   availability_zone: "us-west-2a"
    -   instance_type: "m3.medium"
    -   subnet_id: "subnet-4d70cd28"
    -   security_group_ids: ["sg-7dabec18", "sg-59b6f13c"]
    -   image_id: "ami-b6bdde86"
    -   private_ip_address: "172.25.10.98"
    -   key_name: "scarolan_chef"
```

But when I go into the AWS GUI to look at it, I'm stuck with t1.micro every time

**Comment by bbbco** [comment]
Use:

````
with_machine_options :bootstrap_options => {
     :instance_type => 'm3.medium', ...
}
````

**Comment by dwradcliffe** [comment]
@scarolan looks like you're actually using the fog driver, not the aws driver

**Comment by jkeiser** [comment]
If you are using the fog driver instead of aws, it would fail in this way (fog needs flavor_id, not instance_type, bless you fog).
