### ISSUE TITLE
No resource, method, or local variable named `existing_vpc' when delete security group

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#74]
When I try to delete a security group:

aws_security_group "provisioning-vpc-security-group" do
  action :delete
end

I get:

ERROR: aws_security_group[provisioning-vpc-security-group] (@recipe_files::/home/christine/test/provision/network_aws_delete.rb line 10) had an error: NameError: No resource, method, or local variable named `existing_vpc' for `Chef::Provider::AwsSecurityGroup ""'

I think that 'existing_vpc' should be 'existing_sg' here:
https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_security_group.rb#L35

**Comment by Jimflip** [comment]
Seeing this too, has the side affect that you can't then destroy your VPC due to the dependency.

**Comment by christinedraper** [comment]
I submitted pull request  https://github.com/chef/chef-provisioning-aws/pull/76

**Comment by tyler-ball** [comment]
@Jimflip Does that mean the VPC cannot be `:destroy`ed after this security group is destroyed?  I'm trying to understand which way the dependency goes.

**Comment by christinedraper** [comment]
I suspect @Jimflip means you can't destroy the VPC because the security group wasn't destroyed (you get an EC2 error message saying the VPC still has dependencies i.e. the security group). I had the same thing...

**Comment by Jimflip** [comment]
@christinedraper you are correct.
