### ISSUE TITLE
AWS Profile not honored for aws_vpc (and possibly others)

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#75]
I created an AWS .credentials file with two profiles, one has authority to create VPCs, one didn't. 

I tried various ways to set the profile, including with_driver 'aws:test1' and setting CHEF_DRIVER. In all cases, it ignored the specified profile and used the default one.

The same driver URL worked to set the profile for the machine resource.

When I set a breakpoint in AwsDriver.initialize, it appear not even to be called in the case of aws_vpc, although it is for machine.

I am using chef-provisioning-aws 0.2.1 and chef-provisioning 0.17

**Comment by christinedraper** [comment]
Fairly sure the issue is here in AwsProvider.initialize, because it only uses the default and not the one associated with the profile name in the current driver:

https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_provider.rb#L42

and also here, where it takes the default region and not the one associated with the profile:

https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_provider.rb#L84

**Comment by christinedraper** [comment]
Confirmed this problem applies to other resources (e.g. aws_launch_config)

**Comment by jkeiser** [comment]
As you noticed, this is because these resources apparently don't create drivers at all.  Fixing :)
