### ISSUE TITLE
Error on destroying a loadbalancer

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#82]
With 0.2.1, I create a load balancer:

 load_balancer "webapp-elb" do
 load_balancer_options :availability_zones => ['us-west-1b'],
 :listeners => [{
:port => 80,
:protocol => :http,
:instance_port => 80,
:instance_protocol => :http
},
{
:port => 3301,
:protocol => :tcp,
:instance_port => 3301,
:instance_protocol => :tcp
}
]
machines [ 'bowser' ]
end

When I try to destroy it with:

load_balancer "webapp-elb" do
  action :destroy
end

It deletes the load balancer but fails with an error message:
```
Recipe: @recipe_files::/home/christine/test/provision/scripts/elb_destroy.rb
  * load_balancer[webapp-elb] action destroy[2015-02-02T17:51:30-06:00] INFO: Processing load_balancer[webapp-elb] action destroy (@recipe_files::/home/christine/test/provision/scripts/elb_destroy.rb line 5)

    - Deleting EC2 ELB http://localhost:8889/data/loadbalancers/webapp-elb
    ================================================================================
    Error executing action `destroy` on resource 'load_balancer[webapp-elb]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option action must be equal to one of: nothing, create, delete, nothing!  You passed :destroy.
```

**Comment by christinedraper** [comment]
I think this *may* be an issue with chef-provisioning

https://github.com/chef/chef-provisioning/blob/dd8b19cbea3c4f1c9a4cde93239b26ce9da0709d/lib/chef/provisioning/chef_load_balancer_spec.rb#L79

The ChefLoadBalancerSpec.delete invokes a :destroy action on the chef_data_bag_item, but I think it needs to be :delete

**Comment by lynchc** [comment]
exactly right. I pushed up the change. 

Dude, don't be shy about pushing this kind of thing up yourself :)

**Comment by christinedraper** [comment]
Thanks - still getting oriented - I will get less shy :-)

**Comment by jkeiser** [comment]
Thanks to you both :)  The referenced fix is merged.  I'll get a new version out shortly (possibly Monday).
