### ISSUE TITLE
machine provisioning doesn't work for windows target

### ISSUE THREAD

**Issue by erikvanbrakel** [chef/chef-provisioning-aws#84]
I am quite sure this worked before, but after updating to the latest version, provisioning a windows machine does not use winRM anymore. Here's a sample resource which basically hangs on trying to connect, as it's trying to use SSH instead of winRM:

    windows_ami = 'ami-e99c1d9e'
    machine "MyMachine" do
        machine_options ({
            :image_id => windows_ami,
            :is_windows => true,
            :bootstrap_options => {
                # some stuff here
            },
        })

        role 'WebServer'
    end

I think I've traced it back to this line: https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L370

This was added quite recently (about a week ago), and if we then jump to [line 448](https://github.com/chef/chef-provisioning-aws/blob/5f189d93305fff59f69193d4e1b91dc4cccf0172/lib/chef/provisioning/aws_driver/driver.rb#L448) it's quite obvious that winRM is not implemented there ;-) However, the next statement, machine_for, DOES implement winRM as a transport, see [line 370](https://github.com/chef/chef-provisioning-aws/blob/5f189d93305fff59f69193d4e1b91dc4cccf0172/lib/chef/provisioning/aws_driver/driver.rb#L370).

I can take a stab at fixing it, but do I need to sign a CLA for chef-provisioning for that, just like for the main chef-codebase? If so, I'll need to get that arranged on my side.

-- edit --

On further inspection I have no clue what happened, it's clear that it doesn't work though ;-) Will continue investigating. On second thought, I used the fog:aws one before, so maybe I am confusing things. Either way, the aws_driver.rb file seems to be a bit messy.

**Comment by lynchc** [comment]
This may sound stupid, but bare with me. Can you check to make absolutely sure it's creating a windows box? Since the last release, image_id is not a machine option. it was changed to go into bootstrap_options so that it followed more closely with how the fog provider works.

**Comment by erikvanbrakel** [comment]
Yes, it is a windows machine (but you already found out ;-)). Basically, the aws_driver.rb file is a mess with some missing require directives at the top (InstallMsi is missing), and some pointers which imply winrm is working but it's actually not. Gonna see what it takes to fix it.

**Comment by erikvanbrakel** [comment]
This is no longer relevant with #93 being merged, right?

**Comment by jkeiser** [comment]
I'mma close it since even you think it's no longer relevant.  Thanks much for the fix :)
