### ISSUE TITLE
aws_driver does not honor "with_data_center [region]" setting.

### ISSUE THREAD

**Issue by tschran** [chef/chef-provisioning-aws#85]
We've been following the examples, which all show using "with_data_center" to define a region for a scope.  That works fine for the aws_* resources, like VPCs and subnets, but that region doesn't get respected when we're trying to use machine or load_balancer.  Instead, it will create the instance in a default region, and load_balancers will often fail with an error about the availability zone being invalid.

So, for instance, when I try to run this:

require 'chef/provisioning/aws_driver'
with_driver 'aws'

with_data_center 'eu-west-1' do

  machine 'europe_instance' do
    machine_options :bootstrap_options => {
      }
  end

  load_balancer "europe-elb" do
    load_balancer_options :availability_zones => ['eu-west-1a'],
                          :listeners => [{
                               :port => 80,
                               :protocol => :http,
                               :instance_port => 80,
                               :instance_protocol => :http,
                           }]
  end
end

I get a box spinning up in us-west-2, and an error saying "Invalid Availability Zone: eu-west-1a", even though it should have all built in eu-west-1 because of the "with_data_center" block.  Are we using with_data_center wrong, or is there a workaround for this?

**Comment by Afterglow** [comment]
:+1:  was about to report the same bug myself 

```ruby
require 'chef/provisioning'
require 'chef/provisioning/aws_driver'
 
with_driver 'aws'
 
with_data_center 'eu-west-1' do
  aws_key_pair 'chefprov-eu-west-1-test'
  machine 'chefprov-test' do
    machine_options :bootstrap_options => {
      :key_name => 'chefprov-eu-west-1-test'
    }
  end
end```

Instance gets created in us-east-1 because thats what is set in my .aws/config file as default while the key is created in the correct place.

**Comment by tyler-ball** [comment]
`with_data_center` was removed in 0.4.0.  This is now specified as part of your driver URL.
