### ISSUE TITLE
Re-converging instances that were created with driver version < 0.2.0 fails

### ISSUE THREAD

**Issue by lynchc** [chef/chef-provisioning-aws#86]
I was trying re-converge a machine that had been created with driver version 0.1.3 with the new driver (0.2.1) and was presented with this error:
```
NoMethodError: undefined method `[]' for nil:NilClass
```
After some searching, I tracked down the cause of this issue to commit #713f86e8360fdf5ac5339399d731384e26c89b6b

The code for defining driver_url used to be 
```ruby
def self.canonicalize_url(driver_url, config)
      url = driver_url.split(":")[0]
      [ "aws:#{url}", config ]
end
```

So any recipe that used:
```ruby
with_driver 'aws'
```
would have the chef-provisioning.location.driver_url node attribute set to "aws:aws". Part of this commit was to change how we parse the driver_url to get a credentials profile name and then region.
```ruby
def initialize(driver_url, config)
      super

      scheme, profile_name, region = driver_url.split(':')
      puts "driver_url #{driver_url}.  #{driver_url.split(':').inspect}"
      profile_name = nil if profile_name && profile_name.empty?
      region = nil if region && region.empty?

      credentials = profile_name ? aws_credentials[profile_name] : aws_credentials.default
      @region = region || credentials[:region]
```
This results in profile_name being set to 'aws' so it attempts to set credentials to aws_creds[profile_name] which is nil and raises on the next line.

The workaround I did for this was to knife node edit -a [node] and manually changed the driver_url and driver_version. The next converge happened without issue.

@jkeiser 
The trouble is, after starting at it for a while, I'm still not sure the best way in which to fix this. Any input would be helpful

**Comment by jkeiser** [comment]
@lynchc isn't the driver version written to the location?  One simple way would be to look at the driver version, see if it's < 0.2, and if so, read "aws:aws" as "aws".

**Comment by jkeiser** [comment]
If it isn't written to the location, we should (a) start doing that and (b) special-case "aws:aws" as "aws" for any nodes that don't have a driver version :)

**Comment by tyler-ball** [comment]
Is this still an issue for anyone?  I would love to close this if no one is affected, but am happy to add a workaround if someone needs to migrate from <= 0.1.3 to >= 1.0.0

**Comment by tyler-ball** [comment]
Closing since no one responded to this - please re-open if needed!
