### ISSUE TITLE
machine from_image doesnt pick correct image

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#89]
If I run:

```
machine_image 'appserver_image' do
 # whatever runlist etc
end

machine 'appserver' do
  from_image 'appserver_image'
end
```

The 'appserver' machine is created, but it is using the default image not the newly created one. 

The image_id is expected to be in bootstrap_options, but instead is being set in machine_options (in allocate_machine).

Pull #47 would fix this, but is a breaking change. I'll reopen an alternative pull #87 which would pick up image_id from machine_options if not in bootstrap_options.

**Comment by jkeiser** [comment]
#87 fixed this, correct?  Closing on that assumption.  Please feel free to reopen.
