### ISSUE TITLE
destroying a machine image doesnt delete snapshots

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#94]
I think "unless snapshot.any?" should be "if snapshot.any?"

https://github.com/chef/chef-provisioning-aws/blob/6366ecd1fa0b164736beaa6c2c4208bb11d58495/lib/chef/provisioning/aws_driver/driver.rb#L250

Will try it out and raise a pull request if so

**Comment by christinedraper** [comment]
Made pull request #95

**Comment by jkeiser** [comment]
Associated PR merged, thanks!
